Fish laba
nx33r/laba5 pull request #1
Opened 2022-12-12 18:16 UTC by nx33r

2022-12-19 09:45 UTC, ledan23 requested changes

2022-12-19 09:45 UTC, ledan23 commented on Aquarium.h
> +#pragma once
what is doing?

2022-12-19 18:23 UTC, nx33r commented on Aquarium.h
> +#pragma once
#pragma once - preprocessor directive,
designed to control that a particular file is linked only once during compilation.

2022-12-21 19:27 UTC, ledan23 approved these changes

2023-06-21 21:43 UTC, closed without merging